#!/bin/bash

# Environment for Kailey's ADHD project
# Set up Nipype, FSL, AFNI, Freesurfer, ANTS, MATLAB
module add fsl/5.0.7
module load ANTs/1.9.4
module add freesurfer/5.3.0
module add matlab/2013b/front
module add mricron/6-2013
module add miniconda/2.7
module add afni/openmp
source /home/applications/fsl/5.0.7/etc/fslconf/fsl.sh #This will set up my $FSLDIR

# Set up project-specific python environment
source activate /home/data/nbc/adhd/adhd/env

# Freesurfer project specific subj dir
export SUBJECTS_DIR=/home/tsalo006/Desktop/neurosynth/
# Set ANTs threading to 1
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
# Set Python path to project-specific folder
PYTHONPATH="${PYTHONPATH}:/home/data/nbc/adhd/adhd/"
PATH="${PATH}:/home/applications/freesurfer/bin/"

# Set SPM path
export MATLABCMD="$(which matlab)"
export SPM_PATH=/home/applications/spm12/

export project_name="[ADHD]"
